version: '3.8'

networks:
  monitor-net:
    # driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}
  loki_data: {}
  mysql_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:9.0.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  loki:
    image: grafana/loki:2.5.0
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - ./log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  mysql:
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./log:/var/log
    networks:
      - monitor-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=monitoring
      - MYSQL_USER=exporter
      - MYSQL_PASSWORD=exporter
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    labels:
      org.label-schema.group: "mysql"

  mysqld-exporter:
    image: prom/mysqld-exporter:main
    volumes:
      - ./log:/var/log
    networks:
      - monitor-net
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=root:root@(mysql:3306)/
    depends_on:
      - mysql
    labels:
      org.label-schema.group: "mysql"
